define([], function (app) {
    'use strict';

    function service() {
        var employees = [{ 'name': 'Ram Sharma', 'age': '18', 'email': 'ram.sharma@gmail.com', 'title': 'Developer' },
                    { 'name': 'Mohan Dvivedi', 'age': '12', 'email': 'mohan.dvivedi@gmail.com', 'title': 'Coder' },
                    { 'name': 'Rajat Thakur', 'age': '29', 'email': 'rajat.thakur@gmail.com', 'title': 'Programmer' },
                    { 'name': 'Birender Rawat', 'age': '27', 'email': 'birender.rawat@gmail.com', 'title': 'Analyst' },
                    { 'name': 'Tom Cruse', 'age': '41', 'email': 'tom.cruse@gmail.com', 'title': 'Tester' },
                    { 'name': 'Rik Rohan', 'age': '43', 'email': 'rik.rohan@gmail.com', 'title': 'Manager' },
                    { 'name': 'Priyesh Tiwari', 'age': '28', 'email': 'priyesh.tiwari@gmail.com', 'title': 'IOS Developer' },
                    { 'name': 'Sonam Sagoon', 'age': '30', 'email': 'sonam.sagoon@gmail.com', 'title': 'Android Developer' },
                    { 'name': 'Steve Sokit', 'age': '33', 'email': 'steve.sokit@gmail.com', 'title': 'Tester' },
                    { 'name': 'Goerge Go', 'age': '43', 'email': 'george.go@gmail.com', 'title': 'Tester' },
                    { 'name': 'Hasting Lee', 'age': '45', 'email': 'hasting.lee@gmail.com', 'title': 'Coder' },
                    { 'name': 'Pawan Paul', 'age': '46', 'email': 'pawan.paul@gmail.com', 'title': 'Programmer' },
                    { 'name': 'Rahul Roy', 'age': '47', 'email': 'rahul.roy@gmail.com', 'title': 'Analyst' },
                    { 'name': 'Toni Tik', 'age': '48', 'email': 'tony.tik@gmail.com', 'title': 'Manager' },
                    { 'name': 'Bittu Sharma', 'age': '24', 'email': 'bittu.sharma@gmail.com', 'title': 'Senior Developer' },
                    { 'name': 'Bohan Bo', 'age': '49', 'email': 'bohan.bo@gmail.com', 'title': 'Consultant' },
                    { 'name': 'Anil Sharma', 'age': '24', 'email': 'ram.sharma@gmail.com', 'title': 'R&D Manager' },
                    { 'name': 'Deepak Kumar', 'age': '50', 'email': 'deepak.kumar@gmail.com', 'title': 'People Manager' },
                    { 'name': 'Manoj Dobhal', 'age': '31', 'email': 'manoj.dobhal@gmail.com', 'title': 'Manager' },
                    { 'name': 'Vibhore Tanwer', 'age': '24', 'email': 'vibhore.tanwer@gmail.com', 'title': 'Contractor' },
                    { 'name': 'Shivam Sharma', 'age': '24', 'email': 'shivam.sharma@gmail.com', 'title': 'Lead' },
                    { 'name': 'Prashant Mishra', 'age': '23', 'email': 'prashant.mishra@gmail.com', 'title': 'Senior Associate' },
                    { 'name': 'Mohit Arora', 'age': '21', 'email': 'mohit.arora@gmail.com', 'title': 'Software Engineer' },
                    { 'name': 'Ankur Garg', 'age': '22', 'email': 'ankur.garg@gmail.com', 'title': 'Associate' },
                    { 'name': 'Shelly Aggarwal', 'age': '26', 'email': 'shelly.aggarwal@gmail.com', 'title': 'Tech Lead' },
                    { 'name': 'Anshu Arora', 'age': '27', 'email': 'anshu.arora@gmail.com', 'title': 'HR' },
                    { 'name': 'Rajeeta Kaul', 'age': '32', 'email': 'rajeeta.kaul@gmail.com', 'title': 'IS Management' },
                    { 'name': 'Quaiser Ali', 'age': '37', 'email': 'quiser.ali@gmail.com', 'title': 'Developer' },
                    { 'name': 'Deepika Jagtap', 'age': '42', 'email': 'deepika.jagtap@gmail.com', 'title': 'Acquistion' },
                    { 'name': 'Shailesh Sharma', 'age': '33', 'email': 'shailesh.sharma@gmail.com', 'title': 'Lead' },
                    { 'name': 'Dinesh Arora', 'age': '39', 'email': 'dinesh.arora@gmail.com', 'title': 'Senior Consultant' },
                    { 'name': 'Parveen Sachdeva', 'age': '26', 'email': 'parveen.sachdeva@gmail.com', 'title': 'CEO' },
                    { 'name': 'Prerna Chaturvedi', 'age': '23', 'email': 'prerna.chaturvedi@gmail.com', 'title': 'CTO' },
                    { 'name': 'Himanshu Oberoi', 'age': '34', 'email': 'himanshu.oberoi@gmail.com', 'title': 'Manager' },
                    { 'name': 'Kapil Sharma', 'age': '29', 'email': 'kapil.sharma@gmail.com', 'title': 'Tester' },
                    { 'name': 'Varun Khera', 'age': '30', 'email': 'varun.khera@gmail.com', 'title': 'Programmer' },
                    { 'name': 'John Vid', 'age': '31', 'email': 'john.vid@gmail.com', 'title': 'Admin' },
                    { 'name': 'Scotch Rao', 'age': '25', 'email': 'scotch.rao@gmail.com', 'title': 'Tester' },
                    { 'name': 'Water Melon', 'age': '14', 'email': 'water.melon@gmail.com', 'title': 'Programmer' },
                    { 'name': 'Johny Rodes', 'age': '41', 'email': 'johny.rodes@gmail.com', 'title': 'Coder' },
                    { 'name': 'Thuhin Ghai', 'age': '55', 'email': 'thuhin.ghai@gmail.com', 'title': 'Manager' },
                    { 'name': 'Sonu Sood', 'age': '46', 'email': 'sonu.sood@gmail.com', 'title': 'Tech Lead' },
                    { 'name': 'Siya Soni', 'age': '21', 'email': 'siya.soni@gmail.com', 'title': 'Staff Engineer' },
                    { 'name': 'Seeta Srivastva', 'age': '43', 'email': 'seeta.Srivastva@gmail.com', 'title': 'Principal Engineer' },
                    { 'name': 'Ragini Rohini', 'age': '35', 'email': 'ragini.rohini@gmail.com', 'title': 'Manager' },
                    { 'name': 'Manali Arora', 'age': '33', 'email': 'manali.arora@gmail.com', 'title': 'Analyst' },
                    { 'name': 'Riya Sharma', 'age': '29', 'email': 'riya.sharma@gmail.com', 'title': 'Consultant' },
                    { 'name': 'Reeta Sharma', 'age': '24', 'email': 'reeta.sharma@gmail.com', 'title': 'Senior Consultant' },
                    { 'name': 'Bipasha Bajaj', 'age': '27', 'email': 'bipasha.bajaj@gmail.com', 'title': 'Admin' },
                    { 'name': 'Divya Gumber', 'age': '26', 'email': 'divya.gumber@gmail.com', 'title': 'Tester' },
                    { 'name': 'Neetu Gumber', 'age': '23', 'email': 'neetu.gumber@gmail.com', 'title': 'Programmer' }];

        return employees;
    }
    return service;
});
